---
title: "Khaerie_talks"
date: 2000-02-07
---
title: Khaerie_talks
author: Khareemat Usman
email: kharimat790@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Khaerie_talks is a site for those who are looking for bla bla bla

# social links
twitter_username: @khareemat_Usman
github_username:  khareemat usman
show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
